In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
- 1.How many negative numbers are there?

In [8]:
a[a < 0]

array([-2, -1, -6, -7])

In [12]:
- 2. How many positive numbers are there?

In [13]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [ ]:
- 3. How many even positive numbers are there?

In [15]:
a[(a > 0) & (a % 2 ==0)]

array([ 4, 10, 12])

In [ ]:
-4. If you were to add 3 to each data point, how many positive numbers would there be?

In [22]:
x = a + 3

In [24]:
x[x > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [ ]:
- 5. If you squared each number, what would the new mean and standard deviation be?

In [33]:
y = a ** 2
y.mean(),y.std()

(74.0, 144.0243035046516)

In [ ]:
- 6.A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [36]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [ ]:
- 7.Calculate the z-score for each data point. Recall that the z-score is given by:

In [37]:
import scipy.stats as stats

In [39]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [40]:
- 8. ## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [41]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
sum_of_a = sum(a)

In [45]:
sum_of_a

55

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [46]:
min_of_a = min(a)
min_of_a

1

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [47]:
max_of_a = max(a)
max_of_a

10

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [49]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [70]:
product_of_a = np.product(a)
product_of_a

3628800

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [71]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [72]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [74]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [75]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [83]:
-- setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

SyntaxError: invalid syntax (856825896.py, line 1)

In [85]:
b = np.array([
            [3, 4, 5],
            [6, 7, 8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [88]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [90]:
sum(sum(b))

33