In [4]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
- 1.How many negative numbers are there?

In [8]:
a[a < 0]

array([-2, -1, -6, -7])

In [12]:
- 2. How many positive numbers are there?

In [13]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [ ]:
- 3. How many even positive numbers are there?

In [15]:
a[(a > 0) & (a % 2 ==0)]

array([ 4, 10, 12])

In [ ]:
-4. If you were to add 3 to each data point, how many positive numbers would there be?

In [22]:
x = a + 3

In [24]:
x[x > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [ ]:
- 5. If you squared each number, what would the new mean and standard deviation be?

In [33]:
y = a ** 2
y.mean(),y.std()

(74.0, 144.0243035046516)

In [ ]:
- 6.A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [36]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [ ]:
- 7.Calculate the z-score for each data point. Recall that the z-score is given by:

In [37]:
import scipy.stats as stats

In [39]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [40]:
- 8. ## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [41]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
sum_of_a = sum(a)

In [45]:
sum_of_a

55

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [46]:
min_of_a = min(a)
min_of_a

1

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [47]:
max_of_a = max(a)
max_of_a

10

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [49]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [70]:
product_of_a = np.product(a)
product_of_a

3628800

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [71]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [72]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [74]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [75]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [83]:
-- setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

SyntaxError: invalid syntax (856825896.py, line 1)

In [5]:
b = np.array([
            [3, 4, 5],
            [6, 7, 8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [88]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [90]:
sum(sum(b))

33

In [11]:
b.sum()

33

In [7]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [10]:
b.min()

3

In [13]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [14]:
b.max()

8

In [15]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [16]:
b.mean()

5.5

In [18]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [19]:
b.prod()

20160

In [20]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [35]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [36]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [37]:
b[b % 2 != 0]

array([3, 5, 7])

In [38]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [39]:
b[b % 2 == 0]

array([4, 6, 8])

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [41]:
b.shape

(2, 3)

In [ ]:
# Exercise 10 - transpose the array b.

In [44]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [47]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [48]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [49]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [50]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [57]:
# Exercise 1 - Find the min, max, sum, and product of c.
c.min() , c.max() , c.sum() , c.prod()

(1, 9, 45, 362880)

In [ ]:
# Exercise 2 - Determine the standard deviation of c.

In [58]:
c.std()

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

In [59]:
c.var()

6.666666666666667

In [ ]:
# Exercise 4 - Print out the shape of the array c

In [60]:
c.shape

(3, 3)

In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [62]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

In [67]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [101]:
(c * c.transpose()).sum()

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [102]:
(c * c.transpose()).prod()

131681894400

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [77]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [84]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [87]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [89]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [90]:
d[d < 0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [91]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [94]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [95]:
len(np.unique(d))

11

In [ ]:
# Exercise 8 - Print out the shape of d.

In [96]:
d.shape

(3, 6)

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [98]:
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [99]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])